### ISSUE TITLE
passing object to `autosize` of `n-input` doesn't work

### ISSUE THREAD

**Issue by ifrvn** [becem-gharbi/nuxt-naiveui#32]
i use the example from [naiveui.com](https://www.naiveui.com/en-US/light/components/input#autosize.vue) (with naive-config)
when passing object like `{ minRows: 3, maxRows: 5 }` to `autosize` prop, it doesn't work. no errors in terminal and console
it only works without naive-config

```vue
<template>
  <naive-config>
    <n-space vertical>
      <n-input placeholder="Autosizable" autosize style="min-width: 50%" />
      <n-input
        placeholder="Autosizable"
        type="textarea"
        size="small"
        :autosize="{
          minRows: 3,
          maxRows: 5
        }"
      />
      <n-input
        type="textarea"
        placeholder="Autosizable"
        :autosize="{
          minRows: 3
        }"
      />
    </n-space>
  </naive-config>
</template>
```

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/21982381/041770ea-45b2-423d-9289-1e4f06c46bbf)
![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/21982381/bd8beb28-146c-452b-86b9-1ae29f9a8c91)

### Expected behavior:

![image](https://github.com/becem-gharbi/nuxt-naiveui/assets/21982381/7d7d7758-e43e-4dee-a477-f94ae07ca203)

### versions:

    "@bg-dev/nuxt-naiveui": "^1.5.2",
    "nuxt": "^3.8.1",
    "vue": "^3.3.8",
    "vue-router": "^4.2.5"

**Comment by becem-gharbi** [comment]
Hi, can you describe the issue in english?

**Comment by ifrvn** [comment]
sorry, i've re-edited this issue

**Comment by becem-gharbi** [comment]
It's a bug, thanks for reporting it :)

**Comment by becem-gharbi** [comment]
This issue seems to be related to `naive-ui`. 

The html element `textareaElRef` is used to apply dynamic height based on `autosize` prop. It is set by `updateTextAreaStyle` handler which checks the existence of the element first. Thus styles are only applied client-side when the element is mounted and not on server-side. As a solution, I think we can create a NaiveTextArea component to wrap  NInput and add styles for SSR.

Do you have an idea?

https://github.com/tusen-ai/naive-ui/blob/79cdba591bcdbcf0a0b2dc9f9a6243563ace4a89/src/input/src/Input.tsx#L334

**Comment by ifrvn** [comment]
It did work by overwriting theme config, but the scrollbar is still invisible.

**Comment by becem-gharbi** [comment]
> It did work by overwriting theme config, but the scrollbar is still invisible.

Again this seems to be related to `naive-ui`.

The styles of the internal Scrollbar should be inline. You can set `inline-theme-disabled` to `false` in `NaiveConfig`.

**Comment by ifrvn** [comment]
I see. Thank you so much!
